# Generated by Django 3.0.3 on 2020-03-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200316_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image', models.URLField(default='https://res.cloudinary.com/darbbvujm/image/upload/v1584106702/product_default_nauamx.png')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory')),
            ],
        ),
    ]
